name: GramersGameCore
version: '${project.version}'
main: org.kcsup.gramersgamecore.Main
api-version: 1.17
description: The core plugin for Gramers mingame plugins.
commands:
  arena:
    description: Arena Command
